apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: chat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      name: backend-pod
      namespace: chat-app
      labels:
        app: backend
    spec:
      containers:
      - name: chatapp-backend
        image: aadarshsoni/chatapp-backend:latest
        ports:
        - containerPort: 5001
        env: 
        - name: NODE_ENV
          value: production
        - name: MONGODB_URI  # Add this environment variable
          value: "mongodb://root:root@mongodb-service:27017/dbname?authSource=admin"
        - name: JWT_SECRET  # Add this environment variable
          value: "12345677trty5t"
        - name: PORT  # Add this environment variable
          value: "5001"

