# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: mongodb-pv
#   namespace: chat-app
# spec:
#   accessModes:
#     - ReadWriteOnce
#   capacity:
#     storage: 5Gi
#   hostPath:
#     path: /data 
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain # Best practice to prevent data loss
  hostPath:
    path: /data/mongodb-pv # This path will be on the Minikube VM
  claimRef:
    name: mongodb-pvc
    namespace: chat-app